name: deploy-website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install-dep
      run: |
        sudo apt -y update
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip
	pip3 install markdown2

    - name: gen
      run: |
        ./generate.py

    - name: ssh-key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa

    - name: deploy
      run: | 
        rm -rf .git
        echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        git config --global user.email "noreply@example.com"
        git config --global user.name "deploy-bot"
        cd output
        git init
        git remote add master git@github.com:FurryGamesIndex/FurryGamesIndex.github.io
        git add .
        git commit -m 'deploy website'
        git push -f origin master
