name: deploy-website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: tg-notify
      env:
       TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
       TELEGRAM_TO_EN: ${{ secrets.TELEGRAM_TO_EN }}
       TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        ./scripts/newgame-tg.sh

    - name: install-dep
      run: |
        sudo apt -y update || true
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip python3-setuptools webp
        pip3 install --user git+https://github.com/FurryGamesIndex/python-markdown2

    - name: fix-mtime
      run: |
        ./scripts/fix-mtime.sh

    - name: gen
      run: |
        python3 --version
        python3 -m markdown2 --patch-info
        cwebp -version
        ./generate.py --images-candidate-webp output

    - name: ssh-key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY_RSA }}
         name: id_rsa
         known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: deploy
      run: | 
        mv .git _git
        echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        git config --global user.email "noreply@example.com"
        git config --global user.name "deploy-bot"
        cd output
        git init
        git remote add origin git@github.com:FurryGamesIndex/FurryGamesIndex.github.io
        git add .
        git commit -m 'deploy website'
        git push -f origin master
        cd ..
        rm -rf output
        mv _git .git

    - name: sync-mirror
      run: |
        echo -e "Host gitee.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        git push git@gitee.com:furrygamesindex/games.git master || true
        echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        git push git@gitlab.com:furrygamesindex/games.git master || true
        echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        git push git@bitbucket.org:furrygamesindex/games.git master || true
