name: build-nightly-snapshot

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install-dep
      run: |
        sudo apt -y update
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip zip unzip
        pip3 install markdown2 OpenCC

    - name: download
      run: |
        wget https://github.com/FurryGamesIndex/games/releases/download/_gh_assets/FGI-nightly.zip -O prev.zip || true
        unzip prev.zip || true
        [ -d FGI-nightly ] || echo "warning: getting prev build failed"

    - name: gen
      run: |
        python3 --version
        ./scripts/build-offline-version.sh FGI-nightly
        zip -r output.zip FGI-nightly

    - name: upload-release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output.zip
        asset_name: FGI-nightly.zip
        tag: _gh_assets
        overwrite: true
