name: build-nightly-snapshot

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - '.github/workflows/nightly.yml'

env:
  USELESS_VAR: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install-dep
      run: |
        sudo apt -y update || true
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip python3-setuptools zip unzip
        pip3 install --user git+https://github.com/FurryGamesIndex/python-markdown2
        pip3 install OpenCC

    - name: download
      run: |
        wget https://github.com/FurryGamesIndex/games/releases/download/_gh_assets/FGI-nightly.zip -O prev.zip || true
        unzip prev.zip || true
        [ -d FGI-nightly ] || echo "warning: getting prev build failed"
        mv FGI-nightly FGI-nightly-cache || true

    - name: gen
      env:
        FGI_OFFLINE_WEBP: 1
      run: |
        python3 --version
        python3 -m markdown2 --patch-info
        ./scripts/build-offline-version.sh FGI-nightly FGI-nightly-cache
        zip -r output.zip FGI-nightly
        zip -r output-webp.zip FGI-nightly-webp

    - name: upload-release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output.zip
        asset_name: FGI-nightly.zip
        tag: _gh_assets
        overwrite: true

    - name: upload-release-webp
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output-webp.zip
        asset_name: FGI-nightly-webp.zip
        tag: _gh_assets
        overwrite: true
