name: build-nightly-snapshot

on:
  schedule:
    - cron: "45 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install-dep
      run: |
        sudo apt -y update
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip
        pip3 install markdown2

    - name: gen
      run: |
        python3 --version
        ./scripts/build-offline-version.sh

    - name: upload-release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output
        asset_name: fgi-nightly
        tag: _gh_assert
        overwrite: true
