name: pr-build-check

on:
  pull_request:
    branches: [ master ]

env:
  REPO: git@github.com:FurryGamesIndex/_CI_LIVE_BUILD
  ID: ${{ github.event.pull_request.head.label }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: install-dep
      run: |
        sudo apt -y update || true
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip
        pip3 install --user git+https://github.com/FurryGamesIndex/python-markdown2

    - name: gen
      run: |
        python3 --version
        python3 -m markdown2 --patch-info
        ./generate.py --no-searchdb --no-sitemap "output/${ID}/"
