name: deploy-pr-live

on:
  pull_request:
    branches: [ master ]

env:
  REPO: git@github.com:FurryGamesIndex/_CI_LIVE_BUILD
  ID: ${{ github.event.pull_request.head.label }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: install-dep
      run: |
        sudo apt -y update
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip
        pip3 install markdown2
    - name: ssh-key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY_RSA }}
         name: id_rsa
         known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: pull
      run: |
        mv .git _git
        git clone "${REPO}" output
    - name: gen
      run: |
        python3 --version
        ./generate.py "output/${ID}/"
    - name: deploy
      run: |
        echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        git config --global user.email "noreply@example.com"
        git config --global user.name "deploy-bot"
        cd output
        git add "$ID"
        git commit -m 'deploy website'
        git push -f origin master

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@master
      with:
        message: |
          Hi, thanks for your contribution.
          You will be able to see your changes in automatic build: https://furrygamesindex.github.io/_CI_LIVE_BUILD/${{ env.ID }}/
          嗨，谢谢您的贡献。
          你很快就能从自动构建中看到你的修改：https://furrygamesindex.github.io/_CI_LIVE_BUILD/${{ env.ID }}/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
