name: pr-build-check

on:
  pull_request:
    branches: [ master ]

env:
  REPO: git@github.com:FurryGamesIndex/_CI_LIVE_BUILD
  ID: ${{ github.event.pull_request.head.label }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: tg notify
      if: github.event.action == 'opened'
      run: |
        a="${{ github.event.pull_request.user.login }} 创建了一个 PR。[查看](${{ github.event.pull_request.url }})"
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" --data-urlencode "chat_id=${{ secrets.TELEGRAM_TO }}" --data-urlencode "parse_mode=markdown" --data-urlencode "text=${a}" > /dev/null || true
        
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: install-dep
      run: |
        sudo apt -y update
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip
        pip3 install markdown2

    - name: gen
      run: |
        python3 --version
        ./generate.py --no-searchdb --no-sitemap "output/${ID}/"
